### ISSUE TITLE
Create 5 User Stories

### ISSUE THREAD

**Issue by KasonBraley** [Loki-Code201/PantryPal#5]

**Comment by stefrie** [comment]
## **User Story #1**
- Title
- User Story sentence
- Feature Tasks
- Acceptance Tests

## **User Story #2**
- Title
- User Story sentence
- Feature Tasks
- Acceptance Tests

## **User Story #3**
- Title
- User Story sentence
- Feature Tasks
- Acceptance Tests

## **User Story #4**
- Title
- User Story sentence
- Feature Tasks
- Acceptance Tests

## **User Story #5**
- Title
- User Story sentence
- Feature Tasks
- Acceptance Tests
