### ISSUE TITLE
Color Scheme ideas

### ISSUE THREAD

**Issue by KasonBraley** [Loki-Code201/PantryPal#6]
put your color scheme opinions here

**Comment by ryanemmans** [comment]
<img width="359" alt="Screen Shot 2021-08-02 at 12 21 10 PM" src="https://user-images.githubusercontent.com/86586274/127912536-c61d97cd-7566-4718-a1f6-d249a0ea4d3a.png">

**Comment by ryanemmans** [comment]
<img width="801" alt="Screen Shot 2021-08-02 at 1 01 18 PM" src="https://user-images.githubusercontent.com/86586274/127916982-021289b4-6f6a-4e80-9110-6b426ed407a6.png">

**Comment by stefrie** [comment]
![AdobeColor-Foodwise](https://user-images.githubusercontent.com/54906263/127952450-7c1e75de-c4e1-4f6c-868e-0b650ba11be7.jpeg)
